name: Deploy to Fly.io
on:
    push:
        branches: [main]
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  node-version: '16.9.1'

            - name: Set up Fly CLI
              uses: superfly/flyctl-actions/setup-flyctl@master
              with:
                  version: 1.3

            - name: Deploy app to Fly.io
              run: flyctl deploy --app trivia-bot --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
